#!/usr/bin/env python3

import time
from bitmex_order_dispatcher import server
from bitmex_order_dispatcher.settings import settings

time.sleep(settings.INITIAL_SLEEP_SECONDS)

# Start order dispatcher.
server.start()
