#!/usr/bin/env python3

import time
from bitmex_order_dispatcher import dispatcher_server
from bitmex_order_dispatcher.settings import settings

time.sleep(settings.INITIAL_SLEEP_SECONDS)

# Start order dispatcher.
dispatcher_server.start()
